image: ruby:2.7

cache:
  paths:
  - original-images/
  - public/

before_script:
  - apt install wget graphicsmagick

pages:
  stage: deploy
  script:
  - rake
  artifacts:
    paths:
    - public
  only:
  - master
