#!/usr/bin/env ruby

require 'fileutils'
require 'yaml'


MAX_HEIGHT      = 2048
WGET            = `which wget`.chop
GM              = `which gm`.chop
HOME            = File.expand_path('..', __FILE__)
CONFIG_FILE     = "#{HOME}/sources.yml"
SRC_DIR         = "#{HOME}/original"
THUMBNAIL_DIR   = "#{HOME}/thumbnails"
WALLPAPER_DIR   = "#{HOME}/wallpapers"

def main
  check_requirements
  $config = load_config
  $config.each do |image|
    next if image["source_url"].nil? || image["source_url"] == ""
    download_image(image)
    process_image(image)
  end
end

  #input_path = Pathname.new(input).relative_path_from(Pathname.new(output_dir))
  #output_dir = WALLPAPER_DIR

def process_image(image)
  filename = image_filename(image)
  input    = File.join(SRC_DIR, filename)
  output   = File.join(WALLPAPER_DIR, filename)

  if File.exist?(output)
    if File.mtime(output) <= File.mtime(input)
      FileUtils.rm(output)
    else
      puts "NO CHANGE: %s" % output
      return
    end
  end
  FileUtils.cp(input, output)

  ok = system("gm", "mogrify", "-geometry", "x#{MAX_HEIGHT}", output)
  if ok
    puts "CREATED: %s" % output
  end
end

def download_image(image)
  dest_filename = image_filename(image)
  dest = File.join(SRC_DIR, dest_filename)
  if File.exist?(dest)
    puts "SOURCE EXISTS: #{dest_filename}"
  else
    puts "FETCHING: #{dest_filename}"
    download(from: image["source_url"], to: dest)
  end
end

def download(from:, to:)
  system(WGET, from, "-O", to)
end

def load_config
  YAML.load_file(CONFIG_FILE)
rescue Psych::SyntaxError => exc
  puts "ERROR: could not parse the file #{CONFIG_FILE}:"
  puts exc.to_s
  exit
end

def image_filename(image)
  extension = File.extname(image["source_url"])
  "%s - %s%s" % [image["description"], image["author"], extension]
end

def check_requirements
  if GM == ""
    puts "requirement: apt install graphicsmagick"
  end
end

main()