---
- description: ""
  info_url: ""
  source_url: ""
  thumb_url: ""
  license: ""
  author: ""
  location: ""
  tags: ""

- description: "Alocasia cuprea"
  info_url: "https://commons.wikimedia.org/wiki/File:Alocasia_cuprea_(portrait_orientation).jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Alocasia_cuprea_%28portrait_orientation%29.jpg"
  thumb_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Alocasia_cuprea_%28portrait_orientation%29.jpg/200px-Alocasia_cuprea_%28portrait_orientation%29.jpg"
  license: "CC BY-SA 3.0"
  author: "Frank Schulenburg"
  location: "Hawaii Tropical Botanical Garden"
  tags: "leaf, green, plant"

- description: "Areca trees with vanilla climbers"
  info_url: "https://commons.wikimedia.org/wiki/File:Areca_and_Vanilla_DSC_1306.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Areca_and_Vanilla_DSC_1306.jpg"
  thumb_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Areca_and_Vanilla_DSC_1306.jpg/320px-Areca_and_Vanilla_DSC_1306.jpg"
  license: "CC BY-SA 4.0"
  author: "T.R. Shankar Raman"
  location: "Agumbe, Karnataka Western Ghats, India"
  tags: "trees, green, plant"

- description: "Ponta de São Lourenço"
  info_url: "https://commons.wikimedia.org/wiki/File:Ponta_de_S%C3%A3o_Louren%C3%A7o_north_north_east.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Ponta_de_S%C3%A3o_Louren%C3%A7o_north_north_east.jpg"
  thumb_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Ponta_de_S%C3%A3o_Louren%C3%A7o_north_north_east.jpg/320px-Ponta_de_S%C3%A3o_Louren%C3%A7o_north_north_east.jpg"
  license: "CC BY-SA 3.0"
  author: "Richard Bartz"
  location: "Madeira, Portugal"
  tags: "landscape, ocean, coast, cliff"

- description: "Copacabana"
  info_url: "https://commons.wikimedia.org/wiki/File:Copacabana,_Bolivia.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Copacabana%2C_Bolivia.jpg"
  thumb_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Copacabana%2C_Bolivia.jpg/320px-Copacabana%2C_Bolivia.jpg"
  license: "CC BY-SA 3.0"
  author: "Christopher Crouzet"
  location: "Copacabana, Bolivia"
  tags: "landscape, town, ocean, coast"

- description: "Golden Mountains"
  info_url: "https://commons.wikimedia.org/wiki/File:2015_G%C3%B3ry_Z%C5%82ote_z_Bor%C3%B3wkowej.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/d/d7/2015_G%C3%B3ry_Z%C5%82ote_z_Bor%C3%B3wkowej.jpg"
  thumb_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/2015_G%C3%B3ry_Z%C5%82ote_z_Bor%C3%B3wkowej.jpg/320px-2015_G%C3%B3ry_Z%C5%82ote_z_Bor%C3%B3wkowej.jpg"
  license: "CC BY-SA 3.0"
  author: "Jacek Halicki"
  location: "Śnieżnicki Park Krajobrazowy, Polska"
  tags: "landscape, mountains, snow"

- description: "Echinacea purpurea"
  info_url: "https://commons.wikimedia.org/wiki/File:Echinacea_purpurea,_Jard%C3%ADn_Bot%C3%A1nico,_M%C3%BAnich,_Alemania,_2013-09-08,_DD_01.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/8/88/Echinacea_purpurea%2C_Jard%C3%ADn_Bot%C3%A1nico%2C_M%C3%BAnich%2C_Alemania%2C_2013-09-08%2C_DD_01.jpg"
  thumb_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Echinacea_purpurea%2C_Jard%C3%ADn_Bot%C3%A1nico%2C_M%C3%BAnich%2C_Alemania%2C_2013-09-08%2C_DD_01.jpg/320px-Echinacea_purpurea%2C_Jard%C3%ADn_Bot%C3%A1nico%2C_M%C3%BAnich%2C_Alemania%2C_2013-09-08%2C_DD_01.jpg"
  license: "CC BY-SA"
  author: "Diego Delso"
  location: "Botanical Garden, Munich, Germany"
  tags: "plant, flower, purple"

- description: "Beach"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Beach_by_Renato_Giordanelli.jpg"
  license: "CC BY-SA 3.0"
  author: "Renato_Giordanelli"
  tags: "grey, beach, landscape"

- description: "Bee on Lavender"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Bee_on_lavender_by_Martin.jpg"
  license: "CC BY-SA 3.0"
  author: "Martin"
  tags: "animal, flower, purple"

- description: "Begonia"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Begonia_by_fatpoint21.jpg"
  license: "CC BY-SA 3.0"
  author: "fatpoint21"
  tags: "flower, peach, magenta"

- description: "Below Clouds"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Below_Clouds_by_kobinho.jpg"
  license: "CC BY-SA 3.0"
  author: "kobinho"
  tags: "cloud, sky, blue, weather"

- description: "Berries"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Berries_by_Orb9220.jpg"
  license: "CC BY-SA 3.0"
  author: "Orb9220"
  tags: "red, berry, plant"

- description: "Berries"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Berries_by_Tom_Kijas.jpg"
  license: "CC BY-SA 3.0"
  author: "Tom Kijas"
  tags: "blue, white, berry, plant"

- description: "Bird"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Bird_by_Magnus.jpg"
  license: "CC BY-SA 3.0"
  author: "Magnus"
  tags: "blue, bird, animal"

- description: "Black Hole"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Black_hole_by_Marek_Koteluk.jpg"
  license: "CC BY-SA 3.0"
  author: "Marek Koteluk"
  tags: "blue, abstract"

- description: "Bloom"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Bloom_by_Victor_Madru.jpg"
  license: "CC BY-SA 3.0"
  author: "Victor Madru"
  tags: "plant, flower, white"

- description: "Blue Box Number 2"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Blue_box_number_2_by_orb9220.jpg"
  license: "CC BY-SA 3.0"
  author: "orb9220"
  tags: "grey, blue, texture"

- description: "Blue"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Blue_by_ElSlunko.jpg"
  license: "CC BY-SA 3.0"
  author: "ElSlunko"
  tags: "blue, building, abstract"

- description: "Blue Frost"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Blue_frost_by_ppaabblloo77.jpg"
  license: "CC BY-SA 3.0"
  author: "ppaabblloo77"
  tags: "blue, ice, weather"

- description: "BosqueTK"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/BosqueTK.jpg"
  license: "CC BY-SA 3.0"
  author: "Biker Blue"
  tags: "tree, plant, black, green"

- description: "Stone Mountain"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/brad-huchteman-stone-mountain.jpg"
  license: "CC BY-SA 3.0"
  author: "Brad Huchteman"
  tags: "sun, tree, landscape, green, brown"

- description: "Breaker"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Breaker_by_Lyle_Nel.jpg"
  license: "CC BY-SA 3.0"
  author: "Lyle Nel"
  tags: "machine, grey, blue"

- description: "Brother Typewriter"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Brother_typewriter_by_awdean1.jpg"
  license: "CC BY-SA 3.0"
  author: "awdean1"
  tags: "machine, black"

- description: "Bubbles"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Bubbles_by_JanneM.jpg"
  license: "CC BY-SA 3.0"
  author: "JanneM"
  tags: "abstract, magenta, apple, fruit"

- description: "Busqueda Nocturna"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/BusquedaNocturna.jpg"
  license: "CC BY-SA 3.0"
  author: "Tomás Jorquera Sepúlveda"
  tags: "abstract, green, blue"

- description: "Butterfly"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Butterfly.jpg"
  license: "CC BY-SA 3.0"
  author: "Unknown"
  tags: "animal, butterfly, pastel"

