---
- name: ""
  info_url: ""
  source_url: ""
  thumb_url: ""
  license: ""
  author: ""
  location: ""
  tags: ""

- name: "Areca trees with vanilla climbers"
  info_url: "https://commons.wikimedia.org/wiki/File:Areca_and_Vanilla_DSC_1306.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Areca_and_Vanilla_DSC_1306.jpg"
  thumb_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Areca_and_Vanilla_DSC_1306.jpg/320px-Areca_and_Vanilla_DSC_1306.jpg"
  license: "CC BY-SA 4.0"
  author: "T.R. Shankar Raman"
  location: "Agumbe, Karnataka Western Ghats, India"
  tags: "trees, green, plant"

- name: "Ponta de São Lourenço"
  info_url: "https://commons.wikimedia.org/wiki/File:Ponta_de_S%C3%A3o_Louren%C3%A7o_north_north_east.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Ponta_de_S%C3%A3o_Louren%C3%A7o_north_north_east.jpg"
  thumb_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Ponta_de_S%C3%A3o_Louren%C3%A7o_north_north_east.jpg/320px-Ponta_de_S%C3%A3o_Louren%C3%A7o_north_north_east.jpg"
  license: "CC BY-SA 3.0"
  author: "Richard Bartz"
  location: "Madeira, Portugal"
  tags: "landscape, ocean, coast, cliff"

- name: "Copacabana"
  info_url: "https://commons.wikimedia.org/wiki/File:Copacabana,_Bolivia.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Copacabana%2C_Bolivia.jpg"
  thumb_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Copacabana%2C_Bolivia.jpg/320px-Copacabana%2C_Bolivia.jpg"
  license: "CC BY-SA 3.0"
  author: "Christopher Crouzet"
  location: "Copacabana, Bolivia"
  tags: "landscape, town, ocean, coast"

- name: "Golden Mountains"
  info_url: "https://commons.wikimedia.org/wiki/File:2015_G%C3%B3ry_Z%C5%82ote_z_Bor%C3%B3wkowej.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/d/d7/2015_G%C3%B3ry_Z%C5%82ote_z_Bor%C3%B3wkowej.jpg"
  thumb_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/2015_G%C3%B3ry_Z%C5%82ote_z_Bor%C3%B3wkowej.jpg/320px-2015_G%C3%B3ry_Z%C5%82ote_z_Bor%C3%B3wkowej.jpg"
  license: "CC BY-SA 3.0"
  author: "Jacek Halicki"
  location: "Śnieżnicki Park Krajobrazowy, Polska"
  tags: "landscape, mountains, snow"

- name: "Echinacea purpurea"
  info_url: "https://commons.wikimedia.org/wiki/File:Echinacea_purpurea,_Jard%C3%ADn_Bot%C3%A1nico,_M%C3%BAnich,_Alemania,_2013-09-08,_DD_01.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/8/88/Echinacea_purpurea%2C_Jard%C3%ADn_Bot%C3%A1nico%2C_M%C3%BAnich%2C_Alemania%2C_2013-09-08%2C_DD_01.jpg"
  thumb_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Echinacea_purpurea%2C_Jard%C3%ADn_Bot%C3%A1nico%2C_M%C3%BAnich%2C_Alemania%2C_2013-09-08%2C_DD_01.jpg/320px-Echinacea_purpurea%2C_Jard%C3%ADn_Bot%C3%A1nico%2C_M%C3%BAnich%2C_Alemania%2C_2013-09-08%2C_DD_01.jpg"
  license: "CC BY-SA"
  author: "Diego Delso"
  location: "Botanical Garden, Munich, Germany"
  tags: "plant, flower, purple"

- name: "Sanctuary"
  info_url: "https://commons.wikimedia.org/wiki/File:Sanctuary.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/9/94/Sanctuary.jpg"
  license: "CC BY"
  author: "John D"
  tags: "yellow, plant, flower"

- name: "Aurora Borealis"
  info_url: "https://commons.wikimedia.org/wiki/File:Polarlicht_2.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Polarlicht_2.jpg"
  license: "Public Domain"
  author: "Joshua Strang"
  location: "Bear Lake, Alaska"
  tags: "sky, blue, green, landscape"

- name: "Nasir ol Molk Mosque"
  info_url: "https://commons.wikimedia.org/wiki/File:Nasir-al_molk_-1.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/8/80/Nasir-al_molk_-1.jpg"
  license: "CC BY-SA"
  author: "Ayyoubsabawiki"
  location: "Shiraz, Iran"
  tags: "building"

- name: "Coronal mass ejection"
  info_url: "https://commons.wikimedia.org/wiki/File:Magnificent_CME_Erupts_on_the_Sun_-_August_31.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Magnificent_CME_Erupts_on_the_Sun_-_August_31.jpg"
  license: "CC BY"
  author: "NASA Goddard Space Flight Center"
  tags: "orange, red, celestial"

- name: "Lake Bondhus"
  info_url: "https://commons.wikimedia.org/wiki/File:Lake_Bondhus_Norway_2862.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Lake_Bondhus_Norway_2862.jpg"
  license: "Free Art License"
  author: "Alchemist-hp"
  location: "Norway"
  tags: "landscape, blue, green, weather"

- name: "Osteospermum Barberiae"
  info_url: "https://commons.wikimedia.org/wiki/File:Osteospermum_ecklonis1.JPG"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Osteospermum_ecklonis1.JPG"
  license: "GNU Free Documentation License"
  author: "Joaquim Alves Gaspar"
  tags: "purple, flower"

- name: "New York City At Night"
  info_url: "https://commons.wikimedia.org/wiki/File:New_York_City_at_night_HDR.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/2/22/New_York_City_at_night_HDR.jpg"
  license: "CC BY-SA"
  author: "Paulo Barcellos Jr"
  tags: "landscape, building, grey, black"

- name: "Mostar Old Town"
  info_url: "https://commons.wikimedia.org/wiki/File:Mostar_Old_Town_Panorama_2007.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Mostar_Old_Town_Panorama_2007.jpg"
  license: "GNU Free Documentation"
  author: "Ramirez"
  tags: "green, blue, landscape, building"

- name: "Autumn morning"
  info_url: "https://commons.wikimedia.org/wiki/File:%D0%97%D0%B0_%D1%81%D0%B5%D0%BB%D0%BE%D0%BC_2.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/9/9d/%D0%97%D0%B0_%D1%81%D0%B5%D0%BB%D0%BE%D0%BC_2.jpg"
  license: "CC BY-SA"
  author: "Михайло Пецкович"
  location: "Rakhiv, Ukraine"
  tags: "landscape, orange, green"

- name: "Dead Tree in Sea of Life"
  info_url: "https://commons.wikimedia.org/wiki/File:%D7%A2%D7%A5_%D7%A2%D7%9C_%D7%90%D7%99_%D7%9E%D7%9C%D7%97_%D7%91%D7%90%D7%9E%D7%A6%D7%A2_%D7%99%D7%9D_%D7%94%D7%9E%D7%9C%D7%97.jpg"
  source_url: "https://upload.wikimedia.org/wikipedia/commons/3/30/%D7%A2%D7%A5_%D7%A2%D7%9C_%D7%90%D7%99_%D7%9E%D7%9C%D7%97_%D7%91%D7%90%D7%9E%D7%A6%D7%A2_%D7%99%D7%9D_%D7%94%D7%9E%D7%9C%D7%97.jpg"
  license: "CC BY-SA"
  author: "Amiram Dora"
  location: "Dead Sea"
  tags: "landscape, blue, green"

- name: "Beach"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Beach_by_Renato_Giordanelli.jpg"
  license: "CC BY-SA 3.0"
  author: "Renato_Giordanelli"
  tags: "grey, beach, landscape"

- name: "Bee on Lavender"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Bee_on_lavender_by_Martin.jpg"
  license: "CC BY-SA 3.0"
  author: "Martin"
  tags: "animal, flower, purple"

- name: "Begonia"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Begonia_by_fatpoint21.jpg"
  license: "CC BY-SA 3.0"
  author: "fatpoint21"
  tags: "flower, peach, magenta"

- name: "Below Clouds"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Below_Clouds_by_kobinho.jpg"
  license: "CC BY-SA 3.0"
  author: "kobinho"
  tags: "cloud, sky, blue, weather"

- name: "Berries"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Berries_by_Orb9220.jpg"
  license: "CC BY-SA 3.0"
  author: "Orb9220"
  tags: "red, berry, plant"

- name: "Berries"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Berries_by_Tom_Kijas.jpg"
  license: "CC BY-SA 3.0"
  author: "Tom Kijas"
  tags: "blue, white, berry, plant"

- name: "Bird"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Bird_by_Magnus.jpg"
  license: "CC BY-SA 3.0"
  author: "Magnus"
  tags: "blue, bird, animal"

- name: "Black Hole"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Black_hole_by_Marek_Koteluk.jpg"
  license: "CC BY-SA 3.0"
  author: "Marek Koteluk"
  tags: "blue, abstract"

- name: "Bloom"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Bloom_by_Victor_Madru.jpg"
  license: "CC BY-SA 3.0"
  author: "Victor Madru"
  tags: "plant, flower, white"

- name: "Blue Box Number 2"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Blue_box_number_2_by_orb9220.jpg"
  license: "CC BY-SA 3.0"
  author: "orb9220"
  tags: "grey, blue, texture"

- name: "Blue"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Blue_by_ElSlunko.jpg"
  license: "CC BY-SA 3.0"
  author: "ElSlunko"
  tags: "blue, building, abstract"

- name: "Blue Frost"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Blue_frost_by_ppaabblloo77.jpg"
  license: "CC BY-SA 3.0"
  author: "ppaabblloo77"
  tags: "blue, ice, weather"

- name: "BosqueTK"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/BosqueTK.jpg"
  license: "CC BY-SA 3.0"
  author: "Biker Blue"
  tags: "tree, plant, black, green"

- name: "Stone Mountain"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/brad-huchteman-stone-mountain.jpg"
  license: "CC BY-SA 3.0"
  author: "Brad Huchteman"
  tags: "sun, tree, landscape, green, brown"

- name: "Breaker"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Breaker_by_Lyle_Nel.jpg"
  license: "CC BY-SA 3.0"
  author: "Lyle Nel"
  tags: "machine, grey, blue"

- name: "Brother Typewriter"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Brother_typewriter_by_awdean1.jpg"
  license: "CC BY-SA 3.0"
  author: "awdean1"
  tags: "machine, black"

- name: "Bubbles"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Bubbles_by_JanneM.jpg"
  license: "CC BY-SA 3.0"
  author: "JanneM"
  tags: "abstract, magenta, apple, fruit"

- name: "Busqueda Nocturna"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/BusquedaNocturna.jpg"
  license: "CC BY-SA 3.0"
  author: "Tomás Jorquera Sepúlveda"
  tags: "abstract, green, blue"

- name: "Butterfly"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Butterfly.jpg"
  license: "CC BY-SA 3.0"
  author: "Unknown"
  tags: "animal, butterfly, pastel"

- name: "Cairn"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Cairn_by_Sylvain_Naudin.jpg"
  license: "CC BY-SA 3.0"
  author: "Sylvain Naudin"
  tags: "grey, nature, rocks"

- name: "Carriage Return"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Carriage_Return_by_mendhak.jpg"
  license: "CC BY-SA 3.0"
  author: "mendhak"
  tags: "landscape, cloud, blue, green, building"

- name: "Cedar Waxwing"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Cedar_Wax_Wing_by_Raymond_Lavoie.jpg"
  license: "CC BY-SA 3.0"
  author: "Raymond Lavoie"
  tags: "green, bird"

- name: "Christmas Lights"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Christmas_Lights_by_RaDu_GaLaN.jpg"
  license: "CC BY-SA 3.0"
  author: "RaDu GaLaN"
  tags: "blue, micro, light"

- name: "Clock"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/clock_by_Bernhard_Hanakam.jpg"
  license: "CC BY-SA 3.0"
  author: "Bernhard Hanakam"
  tags: "black, building"

- name: "Cornered"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Cornered.jpg"
  license: "CC BY-SA 3.0"
  author: "Robert Parviainen"
  tags: "pink, flower, plant, micro"

- name: "Crocosmia"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Crocosmia_by_sirpecangum.jpg"
  license: "CC BY-SA 3.0"
  author: "sirpecangum"
  tags: "green, plant, flower, micro"

- name: "Crocus"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Crocus_Wallpaper_by_Roy_Tanck.jpg"
  license: "CC BY-SA 3.0"
  author: "Roy Tanck"
  tags: "green, plant, flower, micro, purple"

- name: "Curls"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/CurlsbyCandy.jpg"
  license: "CC BY-SA 3.0"
  author: "Candy"
  tags: "grey, plant, flower, micro, purple"

- name: "Cyclotron"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Cyclotron_by_cyclotron_beam.jpg"
  license: "CC BY-SA 3.0"
  author: "cyclotron_beam"
  tags: "light, grey"

- name: "Dans Ma Bulle"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Dans_ma_bulle_by_Christophe_Weibel.jpg"
  license: "CC BY-SA 3.0"
  author: "Christophe Weibel"
  tags: "light, abstract, micro"

- name: "Darkening Clockwork"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Darkening_Clockwork_by_Matt_Katzenberger.jpg"
  license: "CC BY-SA 3.0"
  author: "Matt Katzenberger"
  tags: "grey, black, micro, machine"

- name: "Delicate Petals"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Delicate_Petals_by_lefthandgergo.jpg"
  license: "CC BY-SA 3.0"
  author: "lefthandgergo"
  tags: "magenta, orange, flower, plant, micro"

- name: "DSC3907"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/DSC3907_by_Todor_Velichkov.jpg"
  license: "CC BY-SA 3.0"
  author: "Todor_Velichkov"
  tags: "green, plant, micro"

- name: "Early Blossom"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Early_Blossom_by_Dh0r.jpg"
  license: "CC BY-SA 3.0"
  author: "Dh0r"
  tags: "green, plant, micro, flower"

- name: "Early Morning"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Early_Morning_by_Robert_Katzki.jpg"
  license: "CC BY-SA 3.0"
  author: "Robert Katzki"
  tags: "micro, grey, landscape"

- name: "El Haouria"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/El_Haouaria_by_Nusi_Nusi.jpg"
  license: "CC BY-SA 3.0"
  author: "Nusi Nusi"
  tags: "orange, landscape"

- name: "Empty Space"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Empty_Space_by_Glenn_Rayat.jpg"
  license: "CC BY-SA 3.0"
  author: "Glenn Rayat"
  tags: "grey, orange, micro, leaf"

- name: "Encounter"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Encounter_by_Lazardjin.jpg"
  license: "CC BY-SA 3.0"
  author: "Lazardjin"
  tags: "graphic, animal, space"

- name: "Euphoria!"
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: "https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-wallpapers/ubuntu/download/head:/Euphoria%21_by_Tomasino.cz.jpg"
  license: "CC BY-SA 3.0"
  author: "Tomasino.cz"
  tags: "people, light"

- name: ""
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: ""
  license: "CC BY-SA 3.0"
  author: ""
  tags: ""

- name: ""
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: ""
  license: "CC BY-SA 3.0"
  author: ""
  tags: ""

- name: ""
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: ""
  license: "CC BY-SA 3.0"
  author: ""
  tags: ""

- name: ""
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: ""
  license: "CC BY-SA 3.0"
  author: ""
  tags: ""

- name: ""
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: ""
  license: "CC BY-SA 3.0"
  author: ""
  tags: ""

- name: ""
  info_url: "https://launchpad.net/ubuntu-wallpapers"
  source_url: ""
  license: "CC BY-SA 3.0"
  author: ""
  tags: ""

